// Generated by CoffeeScript 1.8.0
(function() {
  "use strict";
  module["export"] = function(grunt) {
    grunt.util.linefeed = '\n';
    return grunt.initConfig({
      pkg: grunt.file.readJSON("package.json"),
      jshint: {
        options: {
          jshintrc: ".jshintrc"
        },
        gruntfile: ["Gruntfile.js"]
      }
    }, require("load-grunt-tasks")(grunt), grunt.registerTask("default", ["jshint"]));
  };

}).call(this);

//# sourceMappingURL=GruntFile.js.map
