// Generated by CoffeeScript 1.8.0
(function() {
  "use strict";
  module.exports = function(grunt) {
    grunt.util.linefeed = '\n';
    grunt.initConfig({
      jshint: {
        options: {
          jshintrc: ".jshintrc"
        },
        gruntfile: ["Gruntfile.js"]
      },
      pkg: grunt.file.readJSON("package.json")
    });
    require("load-grunt-tasks")(grunt);
    grunt.registerTask("default", ["jshint"]);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
